algorithm:
  class: training.algorithms.ppo.PPOAlgorithm

reward:
  class: training.rewards.dense.DenseRewardFunction

scheduler:
  class: training.schedulers.SerialScheduler

seed: 0
total_steps: 5e7
num_envs: 8
envs_per_worker: 16
eval_interval: 1e5
t_window: 8
log_interval: 100

population:
  agents: 4
  generation_steps: 1e5

wandb:
  project: ppo-pop-0
  enabled: true
